### ISSUE TITLE
AppImage from May 7, 2017 crashes on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [chigraph/chigraph-gui#19]
```bash
constantine@linux:~/Desktop$ ./Chigraph-x86_64.AppImage
Segmentation fault (core dumped)
constantine@linux:~/Desktop$ gdb ./Chigraph-x86_64.AppImage
Reading symbols from ./Chigraph-x86_64.AppImage...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/constantine/Desktop/Chigraph-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 3287 is executing new program: /tmp/.mount_GgvwCw/usr/bin/chigraphgui
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdc171700 (LWP 3296)]
[New Thread 0x7fffdae68700 (LWP 3297)]

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00007ffff2926cf8 in llvm::SmallVectorTemplateBase<llvm::cl::parser<llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)>::OptionInfo, false>::grow(unsigned long) ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libLLVM-3.9.so.1
(gdb) bt
#0  0x00007ffff2926cf8 in llvm::SmallVectorTemplateBase<llvm::cl::parser<llvm::ScheduleDAGInstrs* (*)(llvm::MachineSchedContext*)>::OptionInfo, false>::grow(unsigned long) ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libLLVM-3.9.so.1
#1  0x00007ffff2926dcb in ?? () from /tmp/.mount_GgvwCw/usr/bin/../lib/libLLVM-3.9.so.1
#2  0x00007fffd1a1b6a4 in llvm::MachinePassRegistry::Add(llvm::MachinePassRegistryNode*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-4.0.so.1
#3  0x00007fffd16acc9b in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-4.0.so.1
#4  0x00007ffff7de76ba in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffdc68, env=env@entry=0x7fffffffdc78) at dl-init.c:72
#5  0x00007ffff7de77cb in call_init (env=0x7fffffffdc78, argv=0x7fffffffdc68, argc=1, 
    l=<optimized out>) at dl-init.c:30
#6  _dl_init (main_map=main_map@entry=0x94ab50, argc=1, argv=0x7fffffffdc68, env=0x7fffffffdc78)
    at dl-init.c:120
#7  0x00007ffff7dec8e2 in dl_open_worker (a=a@entry=0x7fffffffc8a0) at dl-open.c:575
#8  0x00007ffff7de7564 in _dl_catch_error (objname=objname@entry=0x7fffffffc890, 
    errstring=errstring@entry=0x7fffffffc898, mallocedp=mallocedp@entry=0x7fffffffc88f, 
    operate=operate@entry=0x7ffff7dec4d0 <dl_open_worker>, args=args@entry=0x7fffffffc8a0)
    at dl-error.c:187
#9  0x00007ffff7debda9 in _dl_open (
    file=0x7fffffffcb20 "/usr/lib/x86_64-linux-gnu/dri/r600_dri.so", mode=-2147483390, 
    caller_dlopen=0x7fffea0be989, nsid=-2, argc=<optimized out>, argv=<optimized out>, 
    env=0x7fffffffdc78) at dl-open.c:660
#10 0x00007fffe924ef09 in dlopen_doit (a=a@entry=0x7fffffffcad0) at dlopen.c:66
#11 0x00007ffff7de7564 in _dl_catch_error (objname=0x7b8260, errstring=0x7b8268, 
---Type <return> to continue, or q <return> to quit---
    mallocedp=0x7b8258, operate=0x7fffe924eeb0 <dlopen_doit>, args=0x7fffffffcad0)
    at dl-error.c:187
#12 0x00007fffe924f571 in _dlerror_run (operate=operate@entry=0x7fffe924eeb0 <dlopen_doit>, 
    args=args@entry=0x7fffffffcad0) at dlerror.c:163
#13 0x00007fffe924efa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#14 0x00007fffea0be989 in ?? () from /usr/lib64/libGL.so.1
#15 0x00007fffea0c561b in ?? () from /usr/lib64/libGL.so.1
#16 0x00007fffea099991 in ?? () from /usr/lib64/libGL.so.1
#17 0x00007fffea095522 in glXGetFBConfigs () from /usr/lib64/libGL.so.1
#18 0x00007fffea0968c2 in glXChooseFBConfigSGIX () from /usr/lib64/libGL.so.1
#19 0x00007ffff7fe86d7 in ?? ()
   from /tmp/.mount_GgvwCw/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#20 0x00007ffff7fe89fd in ?? ()
   from /tmp/.mount_GgvwCw/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#21 0x00007ffff7fe5100 in ?? ()
   from /tmp/.mount_GgvwCw/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#22 0x00007fffde355411 in QXcbWindow::create() ()
   from /tmp/.mount_GgvwCw/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#23 0x00007fffde3413a1 in QXcbIntegration::createPlatformWindow(QWindow*) const ()
   from /tmp/.mount_GgvwCw/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#24 0x00007ffff5459c4a in QWindowPrivate::create(bool) ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libQt5Gui.so.5
#25 0x00007ffff5a3a6cd in QWidgetPrivate::create_sys(unsigned long long, bool, bool) ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#26 0x00007ffff5a39e79 in QWidget::create(unsigned long long, bool, bool) ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff5b6d05c in ?? () from /tmp/.mount_GgvwCw/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff5b6d360 in ?? () from /tmp/.mount_GgvwCw/usr/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff5b3a6ca in QMainWindow::menuBar() const ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libQt5Widgets.so.5
#30 0x00007ffff73e5b7e in KXmlGuiWindow::createGUI(QString const&) ()
   from /tmp/.mount_GgvwCw/usr/bin/../lib/libKF5XmlGui.so.5
#31 0x00007ffff73e6d5b in KXmlGuiWindow::setupGUI(QSize const&, QFlags<KXmlGuiWindow::StandardWindowOption>, QString const&) () from /tmp/.mount_GgvwCw/usr/bin/../lib/libKF5XmlGui.so.5
#32 0x00007ffff73e6e52 in KXmlGuiWindow::setupGUI(QFlags<KXmlGuiWindow::StandardWindowOption>, QString const&) () from /tmp/.mount_GgvwCw/usr/bin/../lib/libKF5XmlGui.so.5
#33 0x000000000044bb9c in MainWindow::MainWindow(QWidget*) ()
#34 0x00000000004432e1 in main ()
(gdb)
```

**Comment by russelltg** [comment]
I'm aware of that, the appimages are quite old and need some love.

Flatpak is the most current way to install chigraph, and are quite up to
date. See https://chigraph.io/flatpak/ for the link.

Report any issues you have!

**Comment by russelltg** [comment]
I'm going to close this due to inactivity. if you still have questions or issues, feel free to reopen. Closed.
